name: Despliegue en GitHub Pages

on:
    pull_request:
      branches:
        - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - name: Instalar dependencias
      run: npm i

    - name: Construir la aplicación
      run: npx quasar build

    - name: Desplegar a GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/spa
        publish_branch: gh-pages
        enable_jekyll: false

    - name: Notificar el despliegue exitoso
      run: echo "La aplicación se ha desplegado correctamente en GitHub Pages."
