name: Deploy Quasar in Hostinger

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
    - name: Instalar paquetes LFTP
      run: sudo apt-get install lftp
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npx quasar build
    - name: Configurar FTP
      run: |
        echo "${{ secrets.FTP_HOST }}" >> ftp_host.txt
        echo "${{ secrets.FTP_USERNAME }}" >> ftp_username.txt
        echo "${{ secrets.FTP_PASSWORD }}" >> ftp_password.txt

    # - name: Despliegue en Hostinger
    #   uses: appleboy/ftp-action@v0.2.0
    #   with:
    #     host: ${{ secrets.FTP_HOST }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local_dir: dist/
    #     remote_dir: develop
    #     args: -vv

    - name: Desplegar en Hostinger
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        lftp -c "set ssl:verify-certificate no; open -u $(cat ftp_username.txt),$(cat ftp_password.txt) $(cat ftp_host.txt) && mirror -R --reverse --delete --verbose /dist /develop"
