name: Deploy Quasar in Hostinger

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  deploy-in-production:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npx quasar build -m pwa
    - name: Obtener nombre de la rama
      id: get_branch
      run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
    - name: Configurar FTP
      run: |
        echo "${{ secrets.FTP_HOST }}" >> ftp_host.txt
        echo "${{ secrets.FTP_USERNAME }}" >> ftp_username.txt
        echo "${{ secrets.FTP_PASSWORD }}" >> ftp_password.txt

    - name: Desplegar en Hostinger
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y lftp
        lftp -e "set ssl:verify-certificate no; open $(cat ftp_host.txt); user $(cat ftp_username.txt) $(cat ftp_password.txt); mirror -X .* -X .*/ --reverse --verbose --delete dist/pwa/ ${{ env.BRANCH_NAME }}/; bye"
