name: Despliegue en Hostinger

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalar dependencias
      run: npm i

    - name: Construir la aplicación
      run: npx quasar build -m pwa

    - name: Instalar sshpass
      run: sudo apt-get install -y sshpass

    - name: Desplegar en Hostinger
      run: |
        apt-get update
        apt-get install -y lftp
        lftp -c "open -u ${{ secrets.HOSTINGER_USERNAME }},${{ secrets.HOSTINGER_PASSWORD }} ftp://dixcont.store; mirror -R dist/pwa u448820835@45.93.102.177:/home/u448820835/domains/dixcont.com/develop"
   
    - name: Notificar el despliegue exitoso
      run: echo "La aplicación se ha desplegado correctamente en Hostinger. ${{ secrets.HOSTINGER_PASSWORD }}"

    - name: Limpiar archivos temporales
      run: |
        rm -f sshpass.txt
        unset SSHPASS
