name: Deploy Quasar in Hostinger

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npx quasar build
    - name: Configurar FTP
      run: |
        echo "${{ secrets.FTP_HOST }}" >> ftp_host.txt
        echo "${{ secrets.FTP_USERNAME }}" >> ftp_username.txt
        echo "${{ secrets.FTP_PASSWORD }}" >> ftp_password.txt

    - name: Despliegue en Hostinger
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp://dixcont.com
        username: ${{ secrets.FTP_USERNAME }}
        password: u448820835.dixcont
        local-dir: ./dist/
        server-dir: develop/

    # - name: Desplegar en Hostinger
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y lftp
    #     lftp -c "set ssl:verify-certificate no; open -u $(cat ftp_username.txt),$(cat ftp_password.txt) $(cat ftp_host.txt) && mirror -e -x ^\.git/$ -x ^\.github/$ -x ^\.gitignore$ -x ^\.gitattributes$ -x ^\.editorconfig$ -x ^\.eslintrc.js$ -x ^\.prettierrc.js$ -x ^\.travis.yml$ -x ^\.babel.config.js$ -x ^package-lock.json$ -x ^yarn.lock$ -x ^README.md$ -x ^LICENSE$ -x ^\.env$ -x ^\.env.example$ -x ^\.env.local$ -x ^\.env.development$ -x ^\.env.staging$ -x ^\.env.production$ -x ^node_modules/ /develop"
