name: Despliegue en Hostinger

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalar dependencias
      run: npm i

    - name: Construir la aplicación
      run: npx quasar build -m pwa

    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Desplegar en Hostinger
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "dist/"
        REMOTE_HOST: dixcont.com
        REMOTE_USER: u448820835
        TARGET: "/home/u448820835/domains/dixcont.com"
