name: Despliegue en Hostinger

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalar dependencias
      run: npm i

    - name: Construir la aplicación
      run: npx quasar build -m pwa

    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3

    - name: 📂 Sync Production Config
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: dist/
        TARGET: /home/u448820835/domains/dixcont.com/public_html/develop/
        ARGS: -rlgoDzvc -i -og --chown=user:user
