name: Despliegue de Quasar App en Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalar dependencias
      run: npm ci

    - name: Construir la aplicación
      run: npm run build

    - name: Desplegar a GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: dist

    - name: Notificar el despliegue exitoso
      run: echo "La aplicación se ha desplegado correctamente en la rama gh-pages."
