name: Deploy Quasar in Hostinger

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy-in-github:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event_name == 'push' }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm ci

      - name: Generar archivos de producción
        run: npx quasar build -m pwa

      - name: Despliegue en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: dist/pwa/

      - name: Mostrar URL de la página
        run: echo "El despliegue en GitHub Pages se ha completado. La URL de la página es: https://palma001.github.io/app-dixcont/"
  deploy-in-production:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.0'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npx quasar build -m pwa
    - name: Configurar FTP
      run: |
        echo "${{ secrets.FTP_HOST }}" >> ftp_host.txt
        echo "${{ secrets.FTP_USERNAME }}" >> ftp_username.txt
        echo "${{ secrets.FTP_PASSWORD }}" >> ftp_password.txt

    - name: Desplegar en Hostinger
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y lftp
        lftp -e "set ssl:verify-certificate no; open $(cat ftp_host.txt); user $(cat ftp_username.txt) $(cat ftp_password.txt); mirror -X .* -X .*/ --reverse --verbose --delete dist/pwa/ develop/; bye"
