name: Despliegue en Hostinger

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalar dependencias
      run: npm i

    - name: Construir la aplicación
      run: npx quasar build -m pwa

    - name: Checkout del repositorio
      uses: actions/checkout@v2
      
    - name: Prepare SSH to work with the remote server
      run: |
        cd ~ && mkdir .ssh &&
        touch ~/.ssh/known_hosts &&
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/known_hosts

    - name: Desplegar en Hostinger
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "dist/"
        REMOTE_HOST: u448820835@45.93.102.177
        REMOTE_USER: u448820835
        REMOTE_PORT: 65002
        TARGET: "/home/u448820835/domains/dixcont.com/public_html/devlop/"
