name: Despliegue en Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Instalar dependencias
      run: npm i

    - name: Construir la aplicación
      run: npx quasar build -m pwa

    - name: Desplegar en Hostinger
      run: |
        ssh u448820835@45.93.102.177 "rm -rf /public_html/develop/*"
        scp -r dist/pwa/* u448820835@45.93.102.177:/public_html/develop/

    - name: Notificar el despliegue exitoso
      run: echo "La aplicación se ha desplegado correctamente en Hostinger."
