name: Deploy Quasar in Hostinger

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy-in-github:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm i

      - name: Generar archivos de producción
        run: npx quasar build

      - name: Despliegue en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: dist/spa
