name: Deploy Quasar in Hostinger

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy-in-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm ci

      - name: Generar archivos de producción
        run: npx quasar build -m pwa

      - name: Despliegue en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: dist/pwa/

      - name: Mostrar URL de la página
        run: echo "El despliegue en GitHub Pages se ha completado. La URL de la página es: https://palma001.github.io/app-dixcont/"
