name: Deploy Quasar in Github

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy-in-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm ci

      - name: Generar archivos de producción
        run: npx quasar build

      - name: Despliegue en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: dist/spa
